version: "2"
engines:
   eslint:
     enabled: true
ratings:
   paths: ["webpack-subresource-integrity/index.ts"]
exclude_patterns:
  - "webpack-subresource-integrity/*.js"
  - "wsi-test-helper/*.js"
  - ".git/"
  - ".yarn/"
  - "node_modules/"
  - "**/coverage/"
  - "examples/"
