version: "2"
engines:
  eslint:
    enabled: true
ratings:
  paths:
    [
      "webpack-subresource-integrity/index.ts",
      "webpack-subresource-integrity/plugin.ts",
      "webpack-subresource-integrity/util.ts",
      "webpack-subresource-integrity/reporter.ts",
      "webpack-subresource-integrity/types.ts",
    ]
exclude_patterns:
  - "webpack-subresource-integrity/*.js"
  - "wsi-test-helper/*.js"
  - ".git/"
  - ".yarn/"
  - "node_modules/"
  - "**/coverage/"
  - "examples/"
