language: node_js
node_js:
  - 4
  - 6
  - 8
  - 10
addons:
  firefox: latest
env:
  - WEBPACK_SUFFIX="@1" ETWP_SUFFIX="@1" HWP_SUFFIX="@2"
  - WEBPACK_SUFFIX="@2" ETWP_SUFFIX="@2" HWP_SUFFIX="@2"
  - WEBPACK_SUFFIX="@3" ETWP_SUFFIX="@3" HWP_SUFFIX="@2"
  - WEBPACK_SUFFIX="@4" ETWP_SUFFIX="@4.0.0-alpha.0" HWP_SUFFIX="@3"
matrix:
  exclude:
  - node_js: 4
    env: WEBPACK_SUFFIX="@4" ETWP_SUFFIX="@4.0.0-alpha.0" HWP_SUFFIX="@3"
install:
  - npm install || true
  - npm rm webpack
  - npm rm extract-text-webpack-plugin
  - npm install "webpack""$WEBPACK_SUFFIX" --ignore-scripts || true
  - npm install "extract-text-webpack-plugin""$ETWP_SUFFIX" --ignore-scripts || true
  - npm install "html-webpack-plugin""$HWP_SUFFIX" --ignore-scripts || true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - ./node_modules/karma/bin/karma start --single-run --browsers Firefox
  - $(npm bin)/nyc --reporter=lcovonly $(npm bin)/mocha --exit --timeout 20000
after_script:
  - $(npm bin)/travis-after-all && $(npm bin)/coveralls < ./coverage/lcov.info
