language: node_js
node_js:
  - 0.12
  - 4
  - 5
  - 6
addons:
  firefox: latest
env:
  - WEBPACK_SUFFIX="@1" ETWP_SUFFIX="@1"
  - WEBPACK_SUFFIX="@>=2.2.0-rc <3.0" ETWP_SUFFIX="@>=2.0.0-beta <3.0"
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm rm extract-text-webpack-plugin
  - npm install "webpack""$WEBPACK_SUFFIX" --ignore-scripts || true
  - npm install "extract-text-webpack-plugin""$ETWP_SUFFIX" --ignore-scripts || true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - ./node_modules/karma/bin/karma start --single-run --browsers Firefox
  - ./node_modules/mocha/bin/mocha test/test-webpack.js
