yarnPath: .yarn/releases/yarn-sources.cjs
packageExtensions:
  fastify-static@*:
    peerDependencies:
      fastify: "*"
  html-webpack-include-assets-plugin@*:
    peerDependencies:
      html-webpack-plugin: "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"

