# This workflow runs a smoke test against the latest versions of webpack and
# html-webpack-plugin, daily and on request

name: Compatibility

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Set environmental variables"
        run: |
          echo "PUPPETEER_DOWNLOAD_PATH=$HOME/puppeteer" >> $GITHUB_ENV

      - run: sudo apt-get install -y moreutils
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        id: puppeteer-cache
        with:
          path: ${{ env.PUPPETEER_DOWNLOAD_PATH }}
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('**/yarn.lock') }}

      - run: yarn
      - run: yarn test:smoke
